-- ============================================================
-- CAMPAIGN SEAT
-- RECURRING TASK RUNTIME
-- ============================================================
--
-- Design:
-- 1. Existing task = first occurrence / template source.
-- 2. Recurrence rule snapshots task fields + checklist.
-- 3. Future tasks are generated by pg_cron.
-- 4. Generated tasks are idempotent.
-- 5. Existing generated/completed tasks are never mutated.
-- 6. Dependencies intentionally do NOT copy.
-- ============================================================


-- ============================================================
-- RECURRENCE RULES
-- ============================================================

create table if not exists
public.task_recurrence_rules (
  id uuid primary key
    default gen_random_uuid(),

  workspace_id uuid not null
    references public.workspaces(id)
    on delete cascade,

  created_by uuid not null
    references public.profiles(id)
    on delete restrict,

  template_task_id uuid,

  title text not null,

  description text,

  category text not null
    default 'General',

  priority text not null
    default 'normal',

  visibility text not null
    default 'workspace',

  tags text[] not null
    default '{}'::text[],

  estimated_minutes integer,

  assigned_to uuid
    references public.profiles(id)
    on delete set null,

  checklist_template jsonb not null
    default '[]'::jsonb,

  recurrence_unit text not null,

  interval_count integer not null
    default 1,

  schedule_timezone text not null
    default 'America/New_York',

  start_at timestamptz not null,

  end_at timestamptz,

  next_occurrence_at timestamptz not null,

  last_occurrence_at timestamptz,

  is_enabled boolean not null
    default true,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now(),

  constraint
    task_recurrence_rules_title_valid
    check (
      length(btrim(title))
        between 1 and 180
    ),

  constraint
    task_recurrence_rules_description_valid
    check (
      description is null
      or length(description) <= 5000
    ),

  constraint
    task_recurrence_rules_unit_valid
    check (
      recurrence_unit in (
        'day',
        'week',
        'month'
      )
    ),

  constraint
    task_recurrence_rules_interval_valid
    check (
      interval_count
        between 1 and 365
    ),

  constraint
    task_recurrence_rules_estimate_valid
    check (
      estimated_minutes is null
      or estimated_minutes
        between 1 and 10080
    ),

  constraint
    task_recurrence_rules_checklist_valid
    check (
      jsonb_typeof(
        checklist_template
      ) = 'array'
    ),

  constraint
    task_recurrence_rules_end_valid
    check (
      end_at is null
      or end_at >= start_at
    ),

  constraint
    task_recurrence_rules_next_valid
    check (
      next_occurrence_at >=
        start_at
    ),

  constraint
    task_recurrence_rules_last_valid
    check (
      last_occurrence_at is null
      or last_occurrence_at >=
        start_at
    )
);


create index if not exists
  task_recurrence_rules_workspace_idx
on public.task_recurrence_rules (
  workspace_id,
  created_at desc
);


create index if not exists
  task_recurrence_rules_due_idx
on public.task_recurrence_rules (
  is_enabled,
  next_occurrence_at
)
where is_enabled = true;


-- ============================================================
-- LINK GENERATED TASKS TO THEIR RULE
-- ============================================================

alter table public.tasks
  add column if not exists
    recurrence_rule_id uuid;


alter table public.tasks
  add column if not exists
    recurrence_occurrence_at
      timestamptz;


do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where
      conrelid =
        'public.tasks'::regclass
      and conname =
        'tasks_recurrence_rule_id_fkey'
  ) then
    alter table public.tasks
      add constraint
        tasks_recurrence_rule_id_fkey
      foreign key (
        recurrence_rule_id
      )
      references
        public.task_recurrence_rules(id)
      on delete set null;
  end if;
end
$$;


do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where
      conrelid =
        'public.task_recurrence_rules'::regclass
      and conname =
        'task_recurrence_rules_template_task_id_fkey'
  ) then
    alter table
      public.task_recurrence_rules
      add constraint
        task_recurrence_rules_template_task_id_fkey
      foreign key (
        template_task_id
      )
      references public.tasks(id)
      on delete set null;
  end if;
end
$$;


create unique index if not exists
  tasks_recurrence_occurrence_unique
on public.tasks (
  recurrence_rule_id,
  recurrence_occurrence_at
)
where
  recurrence_rule_id is not null
  and recurrence_occurrence_at
    is not null;


create index if not exists
  tasks_recurrence_rule_idx
on public.tasks (
  recurrence_rule_id,
  recurrence_occurrence_at
);


-- ============================================================
-- ADVANCE RECURRENCE
--
-- Preserves the selected local clock time through DST by
-- converting into the recurrence timezone before adding the
-- interval and converting back to timestamptz.
-- ============================================================

create or replace function
public.advance_task_recurrence_occurrence(
  p_current timestamptz,
  p_unit text,
  p_interval_count integer,
  p_timezone text
)
returns timestamptz
language plpgsql
stable
set search_path =
  pg_catalog,
  public
as $$
declare
  local_current timestamp;
  local_next timestamp;
begin
  if p_current is null then
    raise exception
      'Current recurrence time is required.';
  end if;

  if p_interval_count is null
     or p_interval_count < 1
     or p_interval_count > 365
  then
    raise exception
      'Recurrence interval must be between 1 and 365.';
  end if;

  if p_unit not in (
    'day',
    'week',
    'month'
  ) then
    raise exception
      'Unsupported recurrence unit: %',
      p_unit;
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_timezone_names
    where name = p_timezone
  ) then
    raise exception
      'Unknown recurrence timezone: %',
      p_timezone;
  end if;

  local_current :=
    p_current
      at time zone p_timezone;

  local_next :=
    case p_unit
      when 'day' then
        local_current
        + pg_catalog.make_interval(
            days =>
              p_interval_count
          )

      when 'week' then
        local_current
        + pg_catalog.make_interval(
            days =>
              p_interval_count * 7
          )

      when 'month' then
        local_current
        + pg_catalog.make_interval(
            months =>
              p_interval_count
          )
    end;

  return
    local_next
      at time zone p_timezone;
end;
$$;


revoke all
on function
  public.advance_task_recurrence_occurrence(
    timestamptz,
    text,
    integer,
    text
  )
from public;


revoke all
on function
  public.advance_task_recurrence_occurrence(
    timestamptz,
    text,
    integer,
    text
  )
from anon;


revoke all
on function
  public.advance_task_recurrence_occurrence(
    timestamptz,
    text,
    integer,
    text
  )
from authenticated;


-- ============================================================
-- NORMALIZE / PROTECT RULES
-- ============================================================

create or replace function
public.normalize_task_recurrence_rule()
returns trigger
language plpgsql
security invoker
set search_path =
  pg_catalog,
  public
as $$
begin
  if tg_op = 'UPDATE' then
    if
      new.workspace_id
        is distinct from
          old.workspace_id
      or new.created_by
        is distinct from
          old.created_by
      or new.template_task_id
        is distinct from
          old.template_task_id
    then
      raise exception
        'Recurrence ownership and template are immutable.';
    end if;
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_timezone_names
    where name =
      new.schedule_timezone
  ) then
    raise exception
      'Unknown recurrence timezone: %',
      new.schedule_timezone;
  end if;

  new.title :=
    btrim(new.title);

  new.description :=
    nullif(
      btrim(
        coalesce(
          new.description,
          ''
        )
      ),
      ''
    );

  new.category :=
    coalesce(
      nullif(
        btrim(new.category),
        ''
      ),
      'General'
    );

  new.priority :=
    coalesce(
      nullif(
        btrim(new.priority),
        ''
      ),
      'normal'
    );

  new.visibility :=
    coalesce(
      nullif(
        btrim(new.visibility),
        ''
      ),
      'workspace'
    );

  new.tags :=
    coalesce(
      new.tags,
      '{}'::text[]
    );

  new.checklist_template :=
    coalesce(
      new.checklist_template,
      '[]'::jsonb
    );

  new.updated_at :=
    now();

  return new;
end;
$$;


drop trigger if exists
  normalize_task_recurrence_rule_trigger
on public.task_recurrence_rules;


create trigger
  normalize_task_recurrence_rule_trigger
before insert or update
on public.task_recurrence_rules
for each row
execute function
  public.normalize_task_recurrence_rule();


-- ============================================================
-- RLS
-- ============================================================

alter table
  public.task_recurrence_rules
enable row level security;


drop policy if exists
  "Visible task recurrence rules can be viewed"
on public.task_recurrence_rules;


create policy
  "Visible task recurrence rules can be viewed"
on public.task_recurrence_rules
for select
to authenticated
using (
  (
    template_task_id is not null

    and public.can_view_role_scoped_task(
      template_task_id
    )
  )

  or (
    template_task_id is null

    and public.is_workspace_member(
      workspace_id
    )

    and (
      public.is_workspace_admin(
        workspace_id
      )

      or public.has_campaign_permission(
        workspace_id,
        'tasks.manage_all'
      )

      or created_by =
        auth.uid()

      or assigned_to =
        auth.uid()
    )
  )
);


drop policy if exists
  "Authorized members can create task recurrence rules"
on public.task_recurrence_rules;


create policy
  "Authorized members can create task recurrence rules"
on public.task_recurrence_rules
for insert
to authenticated
with check (
  created_by = auth.uid()

  and public.is_workspace_member(
    workspace_id
  )

  and (
    public.is_workspace_admin(
      workspace_id
    )

    or public.has_campaign_permission(
      workspace_id,
      'tasks.create'
    )

    or public.has_campaign_permission(
      workspace_id,
      'tasks.manage_all'
    )
  )
);


drop policy if exists
  "Authorized members can update task recurrence rules"
on public.task_recurrence_rules;


create policy
  "Authorized members can update task recurrence rules"
on public.task_recurrence_rules
for update
to authenticated
using (
  public.is_workspace_member(
    workspace_id
  )

  and (
    public.is_workspace_admin(
      workspace_id
    )

    or public.has_campaign_permission(
      workspace_id,
      'tasks.manage_all'
    )

    or created_by =
      auth.uid()

    or assigned_to =
      auth.uid()
  )
)
with check (
  public.is_workspace_member(
    workspace_id
  )
);


drop policy if exists
  "Authorized members can delete task recurrence rules"
on public.task_recurrence_rules;


create policy
  "Authorized members can delete task recurrence rules"
on public.task_recurrence_rules
for delete
to authenticated
using (
  public.is_workspace_member(
    workspace_id
  )

  and (
    public.is_workspace_admin(
      workspace_id
    )

    or public.has_campaign_permission(
      workspace_id,
      'tasks.manage_all'
    )

    or created_by =
      auth.uid()
  )
);


-- ============================================================
-- CREATE RECURRENCE FROM AN EXISTING TASK
--
-- The existing task becomes occurrence #1.
-- Future recurrence starts AFTER its current deadline.
-- ============================================================

create or replace function
public.create_task_recurrence_from_task(
  p_task_id uuid,
  p_recurrence_unit text,
  p_interval_count integer
    default 1,
  p_end_at timestamptz
    default null,
  p_schedule_timezone text
    default 'America/New_York'
)
returns public.task_recurrence_rules
language plpgsql
security definer
set search_path =
  pg_catalog,
  public
as $$
declare
  task_record public.tasks%rowtype;

  created_rule
    public.task_recurrence_rules%rowtype;

  checklist_snapshot jsonb;

  next_time timestamptz;

  guard integer := 0;
begin
  if auth.uid() is null then
    raise exception
      'Authentication required.';
  end if;

  select *
  into task_record
  from public.tasks
  where id = p_task_id
  for update;

  if not found then
    raise exception
      'Task not found.';
  end if;

  if not
    public.can_view_role_scoped_task(
      task_record.id
    )
  then
    raise exception
      'Task is not accessible.';
  end if;

  if not (
    public.is_workspace_admin(
      task_record.workspace_id
    )

    or public.has_campaign_permission(
      task_record.workspace_id,
      'tasks.manage_all'
    )

    or task_record.created_by =
      auth.uid()

    or task_record.assigned_to =
      auth.uid()
  ) then
    raise exception
      'You cannot configure recurrence for this task.';
  end if;

  if task_record.recurrence_rule_id
       is not null
  then
    raise exception
      'Task already belongs to a recurrence.';
  end if;

  if task_record.due_at is null then
    raise exception
      'Recurring tasks require a deadline.';
  end if;

  if p_recurrence_unit not in (
    'day',
    'week',
    'month'
  ) then
    raise exception
      'Unsupported recurrence unit.';
  end if;

  if p_interval_count is null
     or p_interval_count < 1
     or p_interval_count > 365
  then
    raise exception
      'Recurrence interval must be between 1 and 365.';
  end if;

  if p_end_at is not null
     and p_end_at <=
       task_record.due_at
  then
    raise exception
      'Recurrence end must be after the first task deadline.';
  end if;

  -- Validates timezone while calculating
  -- the first future occurrence.
  next_time :=
    public.advance_task_recurrence_occurrence(
      task_record.due_at,
      p_recurrence_unit,
      p_interval_count,
      p_schedule_timezone
    );

  -- If recurrence is being attached to an older task,
  -- skip historical missed occurrences instead of
  -- creating a backlog.
  while next_time <= now() loop
    guard := guard + 1;

    if guard > 10000 then
      raise exception
        'Recurrence schedule could not be advanced safely.';
    end if;

    next_time :=
      public.advance_task_recurrence_occurrence(
        next_time,
        p_recurrence_unit,
        p_interval_count,
        p_schedule_timezone
      );
  end loop;

  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'title',
          subtask.title
        )
        order by
          subtask.sort_order,
          subtask.created_at,
          subtask.id
      ),
      '[]'::jsonb
    )
  into checklist_snapshot
  from public.task_subtasks
    as subtask
  where
    subtask.task_id =
      task_record.id
    and subtask.workspace_id =
      task_record.workspace_id;

  insert into
    public.task_recurrence_rules (
      workspace_id,
      created_by,
      template_task_id,

      title,
      description,
      category,
      priority,
      visibility,
      tags,
      estimated_minutes,
      assigned_to,

      checklist_template,

      recurrence_unit,
      interval_count,
      schedule_timezone,

      start_at,
      end_at,

      next_occurrence_at,
      last_occurrence_at,

      is_enabled
    )
  values (
    task_record.workspace_id,
    task_record.created_by,
    task_record.id,

    task_record.title,
    task_record.description,
    coalesce(
      task_record.category,
      'General'
    ),
    coalesce(
      task_record.priority,
      'normal'
    ),
    coalesce(
      task_record.visibility,
      'workspace'
    ),
    coalesce(
      task_record.tags,
      '{}'::text[]
    ),
    task_record.estimated_minutes,
    task_record.assigned_to,

    checklist_snapshot,

    p_recurrence_unit,
    p_interval_count,
    p_schedule_timezone,

    task_record.due_at,
    p_end_at,

    next_time,
    task_record.due_at,

    case
      when
        p_end_at is not null
        and next_time > p_end_at
      then false
      else true
    end
  )
  returning *
  into created_rule;

  update public.tasks
  set
    recurrence_rule_id =
      created_rule.id,

    recurrence_occurrence_at =
      task_record.due_at,

    updated_at =
      now()
  where id =
    task_record.id;

  return created_rule;
end;
$$;


revoke all
on function
  public.create_task_recurrence_from_task(
    uuid,
    text,
    integer,
    timestamptz,
    text
  )
from public;


revoke all
on function
  public.create_task_recurrence_from_task(
    uuid,
    text,
    integer,
    timestamptz,
    text
  )
from anon;


grant execute
on function
  public.create_task_recurrence_from_task(
    uuid,
    text,
    integer,
    timestamptz,
    text
  )
to authenticated;


-- ============================================================
-- PAUSE / RESUME
--
-- Resume skips occurrences missed while paused.
-- ============================================================

create or replace function
public.set_task_recurrence_enabled(
  p_rule_id uuid,
  p_enabled boolean
)
returns public.task_recurrence_rules
language plpgsql
security definer
set search_path =
  pg_catalog,
  public
as $$
declare
  recurrence
    public.task_recurrence_rules%rowtype;

  next_time timestamptz;

  guard integer := 0;
begin
  if auth.uid() is null then
    raise exception
      'Authentication required.';
  end if;

  select *
  into recurrence
  from public.task_recurrence_rules
  where id = p_rule_id
  for update;

  if not found then
    raise exception
      'Recurrence rule not found.';
  end if;

  if not (
    public.is_workspace_admin(
      recurrence.workspace_id
    )

    or public.has_campaign_permission(
      recurrence.workspace_id,
      'tasks.manage_all'
    )

    or recurrence.created_by =
      auth.uid()

    or recurrence.assigned_to =
      auth.uid()
  ) then
    raise exception
      'You cannot change this recurrence.';
  end if;

  if not p_enabled then
    update
      public.task_recurrence_rules
    set
      is_enabled = false,
      updated_at = now()
    where id =
      recurrence.id
    returning *
    into recurrence;

    return recurrence;
  end if;

  next_time :=
    recurrence.next_occurrence_at;

  while next_time <= now() loop
    guard := guard + 1;

    if guard > 10000 then
      raise exception
        'Recurrence schedule could not be resumed safely.';
    end if;

    next_time :=
      public.advance_task_recurrence_occurrence(
        next_time,
        recurrence.recurrence_unit,
        recurrence.interval_count,
        recurrence.schedule_timezone
      );
  end loop;

  update
    public.task_recurrence_rules
  set
    next_occurrence_at =
      next_time,

    is_enabled =
      case
        when
          recurrence.end_at is not null
          and next_time >
            recurrence.end_at
        then false
        else true
      end,

    updated_at =
      now()
  where id =
    recurrence.id
  returning *
  into recurrence;

  return recurrence;
end;
$$;


revoke all
on function
  public.set_task_recurrence_enabled(
    uuid,
    boolean
  )
from public;


revoke all
on function
  public.set_task_recurrence_enabled(
    uuid,
    boolean
  )
from anon;


grant execute
on function
  public.set_task_recurrence_enabled(
    uuid,
    boolean
  )
to authenticated;


-- ============================================================
-- PROCESS RECURRENCES
-- ============================================================

create or replace function
public.process_task_recurrences()
returns integer
language plpgsql
security definer
set search_path =
  pg_catalog,
  public
as $$
declare
  recurrence
    public.task_recurrence_rules%rowtype;

  generated_task_id uuid;

  occurrence_time timestamptz;

  generated_for_rule integer;

  total_generated integer := 0;
begin
  -- Never allow overlapping recurrence processors.
  perform pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'campaign-seat-task-recurrences',
      0
    )
  );

  for recurrence in
    select *
    from public.task_recurrence_rules
    where
      is_enabled = true
      and next_occurrence_at <=
        now()
      and (
        end_at is null
        or next_occurrence_at <=
          end_at
      )
    order by
      next_occurrence_at asc
    for update skip locked
  loop
    generated_for_rule := 0;

    while
      recurrence.next_occurrence_at <=
        now()

      and (
        recurrence.end_at is null
        or recurrence.next_occurrence_at <=
          recurrence.end_at
      )

      and generated_for_rule < 25
    loop
      occurrence_time :=
        recurrence.next_occurrence_at;

      generated_task_id :=
        null;

      insert into public.tasks (
        workspace_id,
        created_by,

        title,
        description,
        category,
        priority,
        visibility,
        tags,
        estimated_minutes,
        due_at,
        assigned_to,

        status,
        is_sample,

        recurrence_rule_id,
        recurrence_occurrence_at
      )
      values (
        recurrence.workspace_id,
        recurrence.created_by,

        recurrence.title,
        recurrence.description,
        recurrence.category,
        recurrence.priority,
        recurrence.visibility,
        recurrence.tags,
        recurrence.estimated_minutes,
        occurrence_time,
        recurrence.assigned_to,

        'open',
        false,

        recurrence.id,
        occurrence_time
      )
      on conflict (
        recurrence_rule_id,
        recurrence_occurrence_at
      )
      where
        recurrence_rule_id is not null
        and recurrence_occurrence_at
          is not null
      do nothing
      returning id
      into generated_task_id;

      if generated_task_id
           is not null
      then
        insert into
          public.task_subtasks (
            workspace_id,
            task_id,
            title,
            is_completed,
            sort_order,
            created_by
          )
        select
          recurrence.workspace_id,
          generated_task_id,

          btrim(
            checklist_item.value
              ->> 'title'
          ),

          false,

          (
            checklist_item.ordinality
            - 1
          )::integer,

          recurrence.created_by
        from
          jsonb_array_elements(
            recurrence.checklist_template
          )
          with ordinality
          as checklist_item(
            value,
            ordinality
          )
        where
          nullif(
            btrim(
              checklist_item.value
                ->> 'title'
            ),
            ''
          ) is not null;

        total_generated :=
          total_generated + 1;
      end if;

      recurrence.last_occurrence_at :=
        occurrence_time;

      recurrence.next_occurrence_at :=
        public.advance_task_recurrence_occurrence(
          occurrence_time,
          recurrence.recurrence_unit,
          recurrence.interval_count,
          recurrence.schedule_timezone
        );

      update
        public.task_recurrence_rules
      set
        last_occurrence_at =
          recurrence.last_occurrence_at,

        next_occurrence_at =
          recurrence.next_occurrence_at,

        is_enabled =
          case
            when
              recurrence.end_at
                is not null
              and
              recurrence.next_occurrence_at >
                recurrence.end_at
            then false
            else is_enabled
          end,

        updated_at =
          now()
      where id =
        recurrence.id;

      generated_for_rule :=
        generated_for_rule + 1;
    end loop;

    if
      recurrence.end_at is not null
      and recurrence.next_occurrence_at >
        recurrence.end_at
    then
      update
        public.task_recurrence_rules
      set
        is_enabled = false,
        updated_at = now()
      where id =
        recurrence.id;
    end if;
  end loop;

  return total_generated;
end;
$$;


revoke all
on function
  public.process_task_recurrences()
from public;


revoke all
on function
  public.process_task_recurrences()
from anon;


revoke all
on function
  public.process_task_recurrences()
from authenticated;


-- ============================================================
-- CRON
-- ============================================================

do $$
declare
  existing_job record;
begin
  for existing_job in
    select jobid
    from cron.job
    where jobname =
      'campaign-seat-task-recurrences'
  loop
    perform cron.unschedule(
      existing_job.jobid
    );
  end loop;
end
$$;


select cron.schedule(
  'campaign-seat-task-recurrences',
  '* * * * *',
  $cron$
    select
      public.process_task_recurrences();
  $cron$
);


-- ============================================================
-- DOCUMENTATION
-- ============================================================

comment on table
  public.task_recurrence_rules
is
  'Recurring task templates and schedules. Existing generated tasks remain independent historical occurrences.';


comment on column
  public.tasks.recurrence_rule_id
is
  'Recurring task rule that generated or owns this task occurrence.';


comment on column
  public.tasks.recurrence_occurrence_at
is
  'Scheduled occurrence timestamp used for recurring-task idempotency.';
